---

- name: get git username
  shell: git config --global --get user.name
  register: git_user_name_result
  changed_when: False
  ignore_errors: yes

- name: get git user email
  shell: git config --global --get user.email
  register: git_user_email_result
  changed_when: False
  ignore_errors: yes

- name: set git username
  shell: git config --global user.name "{{git_user_name}}"
  when: git_user_email_result.stdout != "{{git_user_name}}"

- name: set git user email
  shell: git config --global user.email "{{git_user_email}}"
  when: git_user_email_result.stdout != "{{git_user_email}}"

- name: install homebrew via the curl oneliner
  shell: git clone https://github.com/mxcl/homebrew.git {{ lookup('env','HOME') }}/homebrew
  args:
    creates: "{{ lookup('env','HOME') }}/homebrew/bin/brew"

- name: update and upgrade homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install homebrew cask
  homebrew_tap: tap=caskroom/cask state=present

- name: install homebrew services
  homebrew_tap: tap=homebrew/services state=present
